### ISSUE TITLE
Examples in Documentation don't work

### ISSUE THREAD

**Issue by turimm** [qiao/PathFinding.js#95]
Simple copy/paste to chrome console:
var matrix = [
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 0, 1, 0, 0],
];
var grid = new PF.Grid(matrix);
undefined
var finder = new PF.AStarFinder();
undefined
var path = finder.findPath(1, 2, 4, 2, grid);

pathfinding-browser.min.js:1 Uncaught TypeError: Cannot read property '1' of undefined

**Comment by imor** [comment]
Looks like you are using new docs with an old version. Do any one of the following:
A) Use the latest version 0.4.17 which I just released.

OR

B) Keep using your current version but change this line ```javascript var grid = new PF.Grid(matrix); ``` to ```javascript var grid = new PF.Grid(5, 3, matrix); ```

**Comment by turimm** [comment]
You are right. With new version it works.

**Comment by ssannkkallpp** [comment]
I have version 0.4.17 and it still doesn't work, the same error that turimm displayed comes up. Any idea why?

**Comment by Daeren** [comment]
+ 0.4.18, npm; doesn't work ....

var matrix = [
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
];
var grid = new PF.Grid(matrix); // or = new PF.Grid(5, 3, matrix);
var finder = new PF.AStarFinder();

console.log(finder.findPath(0, 0, 1, 1, grid)); // result: []
